#
# General Settings
#
# Name of the box to be downloaded
box: bento/ubuntu-20.04

#
# Virtual Machine Settings
#
memory: 1024
cpus: 1

#
# Network Settings
#
hostname: local.lamp
ip: 192.168.33.10

#
# Path Settings
#
synced_folder: public
document_root: /var/www/html

#
# Composer
#
composer_version: 2.1.3

#
# Node JS
#
node_version: 10.x
# node_version: 10.x

#
# RubyGems
#
ruby_gems:
  - bundler
  # - wordmove

#
# WordPress Path
#
wp_siteurl: ''  # Path to the WP_SITEURL like "wp"
wp_home: ''     # Path to the WP_HOME like "wp"

#
# WordPress Settings
#
version: latest
lang: en_US
title: Welcome to the Local Wordpress
multisite: false
rewrite_structure: false
# rewrite_structure: /archives/%post_id%

#
# WordPress User
#
admin_user: admin
admin_pass: admin
admin_email: admin@lamp.local

#
# WordPress Database
#
db_prefix: wp_
db_host: localhost
db_name: wordpress
db_user: wordpress
db_pass: wordpress

#
# WordPress Default Plugins
# Plugin's slug or url to the plugin's slug.
#
plugins:
  - classic-editor
# - logbook

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: ''

#
# WordPress Options
#
options:
  blogdescription: Hello Local Wordpress.

#
# WordPress Multisite Options
#
multisite_options: {}

#
# DB will be reset when provision
#
reset_db_on_provision: false

#
# The values of wp-config.php
#
force_ssl_admin: false
wp_debug: true
savequeries: false

gitignore: https://raw.githubusercontent.com/github/gitignore/master/WordPress.gitignore

#
# Additional PHP code in the wp-config.php
#
extra_wp_config: |
  // Additional PHP code in the wp-config.php
  // These lines are inserted by VCCW.
  // You can place additional PHP code here!

#
# Mail Service
#
mailcatcher: true
